# Generated by Django 4.2.6 on 2023-10-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_path_student_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
