# Generated by Django 4.2.6 on 2023-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_actite', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student')),
                ('age', models.PositiveBigIntegerField()),
            ],
        ),
    ]
