# Generated by Django 4.2.6 on 2023-10-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmiosfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-number'], 'verbose_name': 'ÖĞRENCİLER', 'verbose_name_plural': 'ÖĞRENCİLER_LİSTESİ'},
        ),
    ]
